project_id = "kltcbmrzukvjxqkfzbas"

[functions.allocate-tokens]
verify_jwt = false

[functions.consume-tokens]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = false

[functions.send-bulk-sms]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
