project_id = "kltcbmrzukvjxqkfzbas"

[functions.allocate-tokens]
verify_jwt = false

[functions.consume-tokens]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = false
